// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbfA-w8VLyP2o68kGMb4PTaS_y0z0gllQ',
    appId: '1:927113314059:android:f020fb8d4bec3b2f7aec0e',
    messagingSenderId: '927113314059',
    projectId: 'ecomflutter-964e5',
    storageBucket: 'ecomflutter-964e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtWvpNp-dqtwKGmlyqWZ5R6nVGiKlZC-c',
    appId: '1:927113314059:ios:c7009fcabfccb10c7aec0e',
    messagingSenderId: '927113314059',
    projectId: 'ecomflutter-964e5',
    storageBucket: 'ecomflutter-964e5.firebasestorage.app',
    androidClientId: '927113314059-br21eai30ev3shdhf2n22v6umeevapn2.apps.googleusercontent.com',
    iosClientId: '927113314059-5ilip52sa4aork47cmg6627sd9i9fl20.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

}